#!/bin/php
<?php 
require_once("inc/scan_conn.php"); 
require_once("PHPExcel/PHPExcel.php"); 
require_once("evn.php");
// 创建一个处理对象实例      
$objExcel = new PHPExcel();      
// 创建文件格式写入对象实例, uncomment      
$objWriter = new PHPExcel_Writer_Excel5($objExcel);    // 用于其他版本格式      
// or      
//$objWriter = new PHPExcel_Writer_Excel2007($objExcel); // 用于 2007 格式      
//$objWriter->setOffice2003Compatibility(true);      
     
//*************************************      
//设置文档基本属性      
$objProps = $objExcel->getProperties();      
$objProps->setCreator("Zeal Li");      
$objProps->setLastModifiedBy("Zeal Li");      
$objProps->setTitle("Office XLS Test Document");      
$objProps->setSubject("Office XLS Test Document, Demo");      
$objProps->setDescription("Test document, generated by PHPExcel.");      
$objProps->setKeywords("office excel PHPExcel");      
$objProps->setCategory("Test");   

//*************************************      
//设置当前的sheet索引，用于后续的内容操作。      
//一般只有在使用多个sheet的时候才需要显示调用。      
//缺省情况下，PHPExcel会自动创建第一个sheet被设置SheetIndex=0      
$objExcel->setActiveSheetIndex(0);      
     
     
$objActSheet = $objExcel->getActiveSheet();      
     
//设置当前活动sheet的名称      
$objActSheet->setTitle('用户信息');      
     
//*************************************      
//设置单元格内容      
//      
//由PHPExcel根据传入内容自动判断单元格内容类型      
//设置第一行为的字段名称
$fieldName=array(
	"A1"=>"帐号",
	"B1"=>"密码",
	"C1"=>"姓名",
	"D1"=>"证件号码",
	"E1"=>"工作电话",
	"F1"=>"家庭电话",
	"G1"=>"手机号码",
	"H1"=>"电子邮件",
	"I1"=>"联系地址",
	"J1"=>"帐户余额",
	"K1"=>"在线人数",
	"L1"=>"IP 地址",
	"M1"=>"是否绑定MAC",
	"N1"=>"MAC 地址",
	"O1"=>"是否绑定NASIP",
	"P1"=>"NASIP地址",
	"Q1"=>"是否绑定VLAN",
	"R1"=>"VLAN地址",
	"S1"=>"母账号"
);
if(is_array($fieldName)){
	foreach($fieldName as $key=>$value){
		$objActSheet->setCellValue($key,$value);		
	}
}
$result=$db->select_all("u.*,at.*","userinfo as u,userattribute as at","u.ID=at.userID");
if(is_array($result)){
	$row=2;
	foreach($result as $rs){
		$objActSheet->setCellValue("A".$row,$rs["UserName"]);
		$objActSheet->setCellValue("B".$row,$rs["password"]);	
		$objActSheet->setCellValue("C".$row,$rs["name"]);
		$objActSheet->setCellValue("D".$row,$rs["cardid"]);
		$objActSheet->setCellValue("E".$row,$rs["workphone"]);
		$objActSheet->setCellValue("F".$row,$rs["homephone"]);
		$objActSheet->setCellValue("G".$row,$rs["mobile"]);
		$objActSheet->setCellValue("H".$row,$rs["email"]);
		$objActSheet->setCellValue("I".$row,$rs["address"]);
		$objActSheet->setCellValue("J".$row,$rs["money"]);
		$objActSheet->setCellValue("K".$row,$rs["onlinenum"]);
		$objActSheet->setCellValue("L".$row,$rs["ipaddr"]);
		$objActSheet->setCellValue("M".$row,$rs["macbind"]);
		$objActSheet->setCellValue("N".$row,$rs["MAC"]);
		$objActSheet->setCellValue("O".$row,$rs["nasbind"]);
		$objActSheet->setCellValue("P".$row,$rs["nas_ip"]);
		$objActSheet->setCellValue("Q".$row,$rs["vlanbind"]);
		$objActSheet->setCellValue("R".$row,$rs["VLAN"]);
		$objActSheet->setCellValue("S".$row,$rs["Mname"]);
		$row=$row+1;
	}
}

//添加一个新的worksheet      
$objExcel->createSheet();      
$objExcel->getSheet(1)->setTitle('测试2');      
     
//保护单元格      
$objExcel->getSheet(1)->getProtection()->setSheet(true);      
$objExcel->getSheet(1)->protectCells('A1:C22', 'PHPExcel');      
     
     
//*************************************      
//输出内容      
//      
$outputFileName = "PHPExcel/output.xls";      
//到文件      
$objWriter->save($outputFileName);      
//or      
//到浏览器      
//header("Content-Type: application/force-download");      
//header("Content-Type: application/octet-stream");      
//header("Content-Type: application/download");      
//header('Content-Disposition:inline;filename="'.$outputFileName.'"');      
//header("Content-Transfer-Encoding: binary");      
//header("Expires: Mon, 26 Jul 1997 05:00:00 GMT");      
//header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");      
//header("Cache-Control: must-revalidate, post-check=0, pre-check=0");      
//header("Pragma: no-cache");      
//$objWriter->save('php://output');
//echo "文件生成";


?>